### ISSUE TITLE
Be able to filter student list by skills

### ISSUE THREAD

**Issue by Franktian** [fpitt/DCSUPP#20] opened 2015-07-01 20:19 UTC

**Comment by alanyuan0408** [comment] 2016-02-02 16:43
We have finished part of the backend functionality for this feature in User_Controller#Filter_students. The problem is we need to finished the remainder of the frontend functionality of the project.

**Comment by alanyuan0408** [comment] 2016-02-02 16:54
I will just close this issue as it is an overlap with the search for students

**Closed as completed by alanyuan0408** 2016-02-02 16:54 UTC
Labels: professor
